/* AirShield live data client — token stays server-side in Vercel. */
const LIVE_AQI_PATH='/api/air-quality';
const LIVE_SEARCH_PATH='/api/search';
const LIVE_HEALTH_PATH='/api/health';
async function fetchJson(url,options={}){const c=new AbortController(),t=setTimeout(()=>c.abort(),14000);try{const r=await fetch(url,{...options,cache:'no-store',headers:{Accept:'application/json',...(options.headers||{})},signal:c.signal});const raw=await r.text();let j;try{j=JSON.parse(raw)}catch{throw new Error(`Server returned invalid JSON (HTTP ${r.status})`)}if(!r.ok||!j.ok)throw new Error(j.error||`API HTTP ${r.status}`);return j}finally{clearTimeout(t)}}
async function checkLiveService(){try{const j=await fetchJson(LIVE_HEALTH_PATH);return {ok:Boolean(j.ok),tokenConfigured:Boolean(j.tokenConfigured),waqiReachable:Boolean(j.waqiReachable),provider:j.provider||'WAQI',error:j.error||''}}catch(e){return {ok:false,tokenConfigured:false,provider:'WAQI',error:e.message||'Live service unavailable'}}}
async function fetchLiveAQI(cityKey){const d=CITY_DEFS[cityKey];if(!d)throw new Error('Unknown AirShield location');const p=new URLSearchParams({location:d.waqiQuery||d.name});if(d.waqiUid)p.set('uid',String(d.waqiUid));if(d.state)p.set('state',d.state);return (await fetchJson(`${LIVE_AQI_PATH}?${p}`)).data}
async function searchLiveLocations(q){q=String(q||'').trim();if(q.length<2)return [];return (await fetchJson(`${LIVE_SEARCH_PATH}?q=${encodeURIComponent(q)}`)).results||[]}
async function applyLiveData(cityKey){const d=cityData(cityKey);try{const data=await fetchLiveAQI(cityKey),aqi=Number(data?.aqi);if(!Number.isFinite(aqi))throw new Error('Server returned no numeric AQI');const x=data.iaqi||{};d.aqi=aqi;if(Number.isFinite(x.pm25))d.pm25=Math.round(x.pm25);if(Number.isFinite(x.pm10))d.pm10=Math.round(x.pm10);if(Number.isFinite(x.no2))d.no2=Math.round(x.no2);if(Number.isFinite(x.so2))d.so2=Math.round(x.so2);if(Number.isFinite(x.co))d.co=+x.co.toFixed(1);if(Number.isFinite(x.o3))d.o3=Math.round(x.o3);if(Number.isFinite(data.weather?.temp))d.weather.temp=Math.round(data.weather.temp);if(Number.isFinite(data.weather?.hum))d.weather.hum=Math.round(data.weather.hum);if(Number.isFinite(data.weather?.wind))d.weather.wind=+data.weather.wind.toFixed(1);if(Number.isFinite(data.weather?.dir))d.weather.dir=String(data.weather.dir);d.ts=data.timestamp?Date.parse(data.timestamp)||Date.now():Date.now();d.live=true;d.liveError='';d.liveSource=data.source||'WAQI';d.station=data.station||null;return true}catch(e){d.live=false;d.liveError=e.message||'Live API request failed';console.error('[LIVE DATA]',cityKey,d.liveError);return false}}
function updateLiveModeBadge(){const d=CACHE[S.city],b=document.querySelector('[data-live-status]');if(!b)return;if(d?.live){b.textContent=`LIVE · WAQI · ${fmtDateTime(d.ts)}`;b.className='chip tag-live';b.title=d.station?.name?`Station: ${d.station.name}`:'Live WAQI data'}else if(S.dataMode==='api'){b.textContent='LIVE API ERROR';b.className='chip';b.style.color='var(--vpoor)';b.style.borderColor='var(--vpoor)';b.title=d?.liveError||'Live API unavailable'}else{b.textContent='LIVE API';b.className='chip'}}
